Feature/epmldi 1594 elastalert
lean-delivery/ansible-role-aem-elastalert pull request #1
Opened 2020-01-08 12:09 UTC by MaxKavun

Elastalert for alerting based on elasticsearch metrics
https://jira.epam.com/jira/browse/EPMLDI-1594

2020-01-09 12:24 UTC, tgadiev requested changes

2020-01-09 12:24 UTC, tgadiev commented on .gitlab-ci.yml
> +    - aws
```suggestion
    - lint
```

2020-01-09 12:24 UTC, tgadiev commented on .travis.yml
> +  - pip install --upgrade git+https://github.com/ansible/ansible.git@devel docker
```suggestion
  - pip3 install --upgrade ansible==2.8.* docker
```

2020-01-09 12:24 UTC, tgadiev commented on .travis.yml
> +  - pip install molecule==2.22
```suggestion
  - pip3 install molecule==2.22
```

2020-01-09 12:24 UTC, tgadiev commented on .travis.yml
> +  - pip install git+https://github.com/ansible/ansible-lint.git
```suggestion
  - pip3 install git+https://github.com/ansible/ansible-lint.git
```

2020-01-09 12:24 UTC, tgadiev commented on .travis.yml
> +dist: xenial
```suggestion
dist: bionic
```

2020-01-09 12:24 UTC, tgadiev commented on .travis.yml
> +  - "3.6"
```suggestion
  - "3.7"
```

2020-01-09 12:24 UTC, tgadiev commented on molecule/cloud-aws-direct/molecule.yml
> +  - name: test-aws-centos7-filebeat
filebeat?

2020-01-09 15:02 UTC, MaxKavun commented on molecule/cloud-aws-direct/molecule.yml
> +  - name: test-aws-centos7-filebeat
Fixed ! Thanks

2020-01-13 14:28 UTC, tgadiev requested changes

2020-01-13 14:28 UTC, tgadiev commented on README.md
> +    - role: ansible-role-aem-monitoring
```suggestion
    - role: ansible-role-aem-elastalert
```

2020-01-13 14:28 UTC, tgadiev commented on README.md
> +    - role: ansible-role-aem-monitoring
```suggestion
    - role: ansible-role-aem-elastalert
```

2020-01-13 14:28 UTC, tgadiev commented on README.md
> +    - role: ansible-role-aem-monitoring
```suggestion
    - role: ansible-role-aem-elastalert
```

2020-01-14 07:50 UTC, MaxKavun commented on README.md
> +    - role: ansible-role-aem-monitoring
Fixed, thanks

2020-01-29 09:00 UTC, tgadiev approved these changes

2020-01-29 10:18 UTC, merged